---
- name: Deploy Container docker
  hosts: localhost
  become: true

  tasks:
    - name: deploy application
      command: docker run --name edureka-project1-application --rm -itd -p 8095:80 llorenckaferocks/edureka-project1:1.0
