---
- name: Deploy Container docker
  hosts: localhost
  become: true

  tasks:
    - name: deploy application
      command: docker run --name edureka-project1-application -itd -p 8081:80 llorenckaferocks/edureka-project1::1.0