---
- name: Install docker
  hosts: localhost
  become: true

  tasks:
    - name: get previous docker package
      get_url:
        url: "https://launchpadlibrarian.net/468715393/docker.io_19.03.8-0ubuntu1_amd64.deb"
        dest: /root/

    - name: stop docker service
      command: systemctl stop docker

    - name: Install Docker package using .deb file
      command: yes | dpkg -i /root/docker.io_19.03.8-0ubuntu1_amd64.deb

    - name: start docker service
      command: systemctl start docker