---
- name: Install docker
  hosts: localhost
  become: true

  tasks:
    - name: update apt
      command: apt update

    - name: install docker engine
      command: apt install -y docker.io

    - name: start docker service
      command: systemctl start docker