---
- name: Install docker
  hosts: localhost
  become: true

  tasks:
    - name: get previous docker package
      get_url:
        url: "https://launchpadlibrarian.net/468715393/docker.io_19.03.8-0ubuntu1_amd64.deb"
        dest: ~/

    - name: Install Docker package using .deb file
      command: dpkg -i ~/docker.io_19.03.8-0ubuntu1_amd64.deb

    - name: restart docker service
      command: systemctl restart docker