---
- name: Remove Container docker
  hosts: localhost
  become: true

  tasks:
    - name: Stop Container
      command: true || sudo docker container stop edureka-project1-application

    - name: Remove Container
      command: true || sudo docker container rm --force edureka-project1-application